### ISSUE TITLE
V0.2.0 Feature Plan

### ISSUE THREAD

**Issue by jdneo** [jdneo/vscode-checkstyle#50]
- [x] Resolve checkstyle jar automatically #18 
- [x] Can set enable/disable autocheck through command #33 
- [x] Can set property file setting through command #34
- [x] Do not show operation canceled error when it is UserCancelError #35
- [x] Change Log should be packaged into *.vsix #36
- [x] add status bar item to trigger checkstyle and show status #45
