### ISSUE TITLE
0.4.0 feature plan

### ISSUE THREAD

**Issue by jdneo** [jdneo/vscode-checkstyle#90]
- [x] Add language server error state into the status icon (#78)
- [x] Add open output channel action to the status icon (#78)
- [x] Can open download page when download failed (#79)
- [x] Add don't warning again option when invalid Checkstyle version warning pop up. (#80)
- [x] Change checkstyle command name (#93 )

**Comment by jdneo** [comment]
Close this issue since all of the planned features are implemented and merged.
